#include "printf.h"
#include <limits.h>

int	main(void)
{
	int	count;
	char	*temp;

	//no format
	printf("\n=======>No format<=========\n");
	count = printf("");
	printf("%d", count);
	printf("\n");
	count = printf("\x01\x02\a\v\b\f\r\n");
	printf("%d", count);
	printf("\n");
	count = printf("coucou");
	printf("%d", count);
	printf("\n");
	count = printf("#nyancat inside");
	printf("%d", count);
	printf("\n");
	count = printf("\x7f");
	printf("%d", count);
	printf("\n");
	count = printf("The Game.");
	printf("%d", count);
	printf("\n");
	count = printf("I know what you are doing.");
	printf("%d", count);
	printf("\n");
	count = printf("You should better not go to sleep.");
	printf("%d", count);
	printf("\n");
	count = printf("Drop the keyboard and RUN!");
	printf("%d", count);
	printf("\n");
	count = printf("Any invalid command will remove a random file from your home.");
	printf("%d", count);
	printf("\n");
	count = printf("You will die before this tests ends.");
	printf("%d", count);
	printf("\n");
	count = printf("I love the smell of bugs in the morning.");
	printf("%d", count);
	printf("\n");
	count = printf("What do you want to debug today?");
	printf("%d", count);
	printf("\n");
	count = printf("rm: /: Permission denied.");
	printf("%d", count);
	printf("\n");
	count = printf("Already up-to-date.");
	printf("%d", count);
	printf("\n");
	count = printf(":(){ :|:& };:");
	printf("%d", count);
	printf("\n");
	count = printf("Do you want to print 333.5K chars? (y/N)");
	printf("%d", count);
	printf("\n");
	count = printf("Try with ASAN, and be amazed");
	printf("%d", count);
	printf("\n");
	count = printf("Remember that word: C H A I R");
	printf("%d", count);
	printf("\n");
	count = printf("Good morning, pal *<:-)");
	printf("%d", count);
	printf("\n");
	count = printf("WASTED");
	printf("%d", count);
	printf("\n");
	count = printf("Too old to crash");
	printf("%d", count);
	printf("\n");
	count = printf("don’t feed the bugs! (except delicious stacktraces)!");
	printf("%d", count);
	printf("\n");
	count = printf("Beer in mind.");
	printf("%d", count);
	printf("\n");
	count = printf("3nl4r9e y0\\/r pr1ntf");
	printf("%d", count);
	printf("\n");
	count = printf("Don't do this.");
	printf("%d", count);
	printf("\n");
	count = printf("No fix, no sleep");
	printf("%d", count);
	printf("\n");
	count = printf("/dev/brain: No such file or directory.");
	printf("%d", count);
	printf("\n");
	count = printf("こんにちは、私はprintf単体テストです");
	printf("%d", count);
	printf("\n");
	count = printf("いいえ");
	printf("%d", count);
	printf("\n");
	count = printf("最終的なフラッシュ");
	printf("%d", count);
	printf("\n");
	count = printf("(╯°□°)╯︵ ┻━┻ ");
	printf("%d", count);
	printf("\n");
	count = printf("(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)");
	printf("%d", count);
	printf("\n");
	count = printf("┬─┬﻿ ノ( ゜-゜ノ)");
	printf("%d", count);
	printf("\n");
	count = printf("(╯°Д°）╯︵ /(.□ . \\)");
	printf("%d", count);
	printf("\n");
	count = printf("(/ .□.)\\ ︵╰(゜Д゜)╯︵ /(.□. \\)");
	printf("%d", count);
	printf("\n");
	count = printf("ʕノ•ᴥ•ʔノ ︵ ┻━┻");
	printf("%d", count);
	printf("\n");


	//char
	printf("\n=======>CHAR format<=========\n");
	count = printf("%c", '0');
	printf("%d", count);
	printf("\n");
	count = printf(" %c ", '0');
	printf("%d", count);
	printf("\n");
	count = printf(" %c", '0' - 256);
	printf("%d", count);
	printf("\n");
	count = printf("%c ", '0' + 256);
	printf("%d", count);
	printf("\n");
	count = printf(" %c %c %c ", '0', '2', '1');
	printf("%d", count);
	printf("\n");
	count = printf(" %c %c %c ", ' ', ' ', ' ');
	printf("%d", count);
	printf("\n");
	count = printf(" %c %c %c ", '1', '2', '3');
	printf("%d", count);
	printf("\n");
	count = printf(" %c %c %c ", '2', '1', '0');
	printf("%d", count);
	printf("\n");
	count = printf(" %c %c %c ", '0', '1', '2');
	printf("%d", count);
	printf("\n");
	count =  printf("%c", 'x');
	printf("%d", count);
	printf("\n");
	count = printf(" %c", 'x');
	printf("%d", count);
	printf("\n");
	count = printf("%c ", 'x');
	printf("%d", count);
	printf("\n");
	count = printf("%c%c%c", 'a', '\t', 'b');
	printf("%d", count);
	printf("\n");
	count = printf("%cc%cc%c", 'a', '\t', 'b');
	printf("%d", count);
	printf("\n");
	count = printf("%cs%cs%c", 'c', 'b', 'a');
	printf("%d", count);
	printf("\n");
	
	
	
	
	
	


	//str
	printf("\n=======>STR format<=========\n");
	char *s2 = "Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Atirei o pau no gatis, per gatis num morreus.";
	count = printf("%s", "");
	printf("%d", count);
	printf("\n");
	count = printf(" %s", "");
	printf("%d", count);
	printf("\n");
	count = printf("%s ", "");
	printf("%d", count);
	printf("\n");
	count = printf(" %s ", "");
	printf("%d", count);
	printf("\n");
	count = printf(" %s ", "-");
	printf("%d", count);
	printf("\n");
	count = printf(" %s %s ", "", "-");
	printf("%d", count);
	printf("\n");
	count = printf(" %s %s ", " - ", "");
	printf("%d", count);
	printf("\n");
	count = printf(" %s %s %s %s %s", " - ", "", "4", "", s2);
	printf("%d", count);
	printf("\n");
	count = printf(" %s %s %s %s %s ", " - ", "", "4", "", "2 ");
	printf("%d", count);
	printf("\n");
	count =  printf(" NULL %s NULL ", NULL);
	printf("%d", count);
	printf("\n");
	count = printf("%s", "");
	printf("%d",count);
	printf("\n");
	count = printf("%s", (char *)NULL);
	printf("%d",count);
	printf("\n");
	count = printf("%s", "some string with %s hehe");
	printf("%d",count);
	printf("\n");
	count = printf(" %s", "can it handle \t and \n?");
	printf("%d",count);
	printf("\n");
	count = printf("%sx", "{} al$#@@@^&$$^#^@@^$*((&");
	printf("%d",count);
	printf("\n");
	count = printf("%s%s%s", "And ", "some", "joined");
	printf("%d",count);
	printf("\n");
	count = printf("%ss%ss%ss", "And ", "some other", "joined");
	printf("%d",count);
	printf("\n");




	// %%
printf("\n=======>%% format<=========\n");
	count = printf("%%");
	printf("%d", count);
	printf("\n");
	count = printf(" %%");
	printf("%d", count);
	printf("\n");
	count = printf("%%c");
	printf("%d", count);
	printf("\n");
	count = printf("%%%%%%");
	printf("%d", count);
	printf("\n");
	count = printf("%%%c", 'x');
	printf("%d", count);
	printf("\n");

// address pointers
printf("\n=======>POINTERS format<=========\n");

	count = printf("%p",NULL);
	printf("%d", count);
	printf("\n");
	count = printf("%p",(void *)-14523);
	printf("%d", count);
	printf("\n");
	count = printf("%p",(void *)ULONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf("%p",(void *)LONG_MAX + 423856);
	printf("%d", count);
	printf("\n");
	count = printf("%p",(void *)0);
	printf("%d", count);
	printf("\n");
	count = printf("%p",(void *)INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf("%p",-1);
	printf("%d", count);
	printf("\n");
	count = printf("%p",1);
	printf("%d", count);
	printf("\n");
	count = printf("%p",2);
	printf("%d", count);
	printf("\n");
	count = printf("%p",3);
	printf("%d", count);
	printf("\n");
	count = printf("%p",4);
	printf("%d", count);
	printf("\n");
	count = printf("%p",5);
	printf("%d", count);
	printf("\n");
	count = printf("%p",6);
	printf("%d", count);
	printf("\n");
	count = printf("%p",7);
	printf("%d", count);
	printf("\n");
	count = printf("%p",8);
	printf("%d", count);
	printf("\n");
	count = printf("%p",9);
	printf("%d", count);
	printf("\n");
	count = printf("%p",10);
	printf("%d", count);
	printf("\n");
	count = printf("%p", 11);
	printf("%d", count);
	printf("\n");
	count = printf("%p",12);
	printf("%d", count);
	printf("\n");
	count = printf("%p",13);
	printf("%d", count);
	printf("\n");
	count = printf("%p",14);
	printf("%d", count);
	printf("\n");
	count = printf("%p",15);
	printf("%d", count);
	printf("\n");
	count = printf("%p",16);
	printf("%d", count);
	printf("\n");
	count = printf("%p",15);
	printf("%d", count);
	printf("\n");
	count = printf("%p",16);
	printf("%d", count);
	printf("\n");
	count = printf("%p",17);
	printf("%d", count);
	printf("\n");
	count = printf("%p",LONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf("%p",LONG_MIN);
	printf("%d", count);
	printf("\n");
	count = printf("%p",INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf("%p",ULONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf("%p",-ULONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf("%p",0);
	printf("%d", count);
	printf("\n");


	// address decimal %d
	printf("\n=======>%%d format<=========\n");
	count = printf("%d", 0);
	printf("%d", count);
	printf("\n");
	count = printf("%d", -10);
	printf("%d", count);
	printf("\n");
	count = printf("%d", -200000);
	printf("%d", count);
	printf("\n");
	count = printf("%d", -6000023);
	printf("%d", count);
	printf("\n");
	count = printf("%d", 10);
	printf("%d", count);
	printf("\n");
	count = printf("%d", 10000);
	printf("%d", count);
	printf("\n");
	count = printf("%d", 100023);
	printf("%d", count);
	printf("\n");
	count = printf("%d", INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf("%d", INT_MIN);
	printf("%d", count);
	printf("\n");
	count = printf("dgs%dxx", 10);
	printf("%d", count);
	printf("\n");
	count = printf("%d%dd%d", 1, 2, -3);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 0);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -1);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 1);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 9);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 10);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 11);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 15);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 16);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 17);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 99);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 100);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 101);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -9);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -10);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -11);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -14);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -15);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -16);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -99);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -100);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", -101);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", INT_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", LONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", LONG_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", UINT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", ULONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %d ", 9223372036854775807LL);
	printf("%d", count);
	printf("\n");
	count = printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	printf("%d", count);
	printf("\n");


	// address decimal %i
	printf("\n=======>%%i format<=========\n");
	count = printf("%i", 0);
	printf("%i", count);
	printf("\n");
	count = printf("%i", -10);
	printf("%i", count);
	printf("\n");
	count = printf("%i", -200000);
	printf("%i", count);
	printf("\n");
	count = printf("%i", -6000023);
	printf("%i", count);
	printf("\n");
	count = printf("%i", 10);
	printf("%i", count);
	printf("\n");
	count = printf("%i", 10000);
	printf("%i", count);
	printf("\n");
	count = printf("%i", 100023);
	printf("%i", count);
	printf("\n");
	count = printf("%i", INT_MAX);
	printf("%i", count);
	printf("\n");
	count = printf("%i", INT_MIN);
	printf("%i", count);
	printf("\n");
	count = printf("dgs%ixx", 10);
	printf("%i", count);
	printf("\n");
	count = printf("%i%id%i", 1, 2, -3);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 0);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -1);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 1);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 9);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 10);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 11);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 15);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 16);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 17);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 99);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 100);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 101);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -9);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -10);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -11);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -14);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -15);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -16);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -99);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -100);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", -101);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", INT_MAX);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", INT_MIN);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", LONG_MAX);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", LONG_MIN);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", UINT_MAX);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", ULONG_MAX);
	printf("%i", count);
	printf("\n");
	count = printf(" %i ", 9223372036854775807LL);
	printf("%i", count);
	printf("\n");
	count = printf(" %i %i %i %i %i %i %i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	printf("%i", count);
	printf("\n");

	// address unsigned int %u
	printf("\n=======>%%u format<=========\n");

	count = printf(" %u ", 0);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -1);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 1);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 9);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 10);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 11);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 15);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 16);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 17);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 99);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 100);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 101);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -9);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -10);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -11);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -14);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -15);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -16);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -99);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -100);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", -101);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", INT_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", LONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", LONG_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", UINT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", ULONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %u ", 9223372036854775807LL);
	printf("%d", count);
	printf("\n");
	count = printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	printf("%d", count);
	printf("\n");
	count = printf("%u", 42);
    printf("%d", count);
    printf("\n");
	count = printf("before %u after", 42);
    printf("%d", count);
    printf("\n");
	count = printf("%u%u%u%u%u", 1, 100, 999, 42, 999988888);
    printf("%d", count);
    printf("\n");
	count = printf("a%ub%uc%ud", 0, 55555, 100000);
    printf("%d", count);
    printf("\n");
	count = printf("%u", UINT_MAX);
    printf("%d", count);
    printf("\n");


	// address hexa low %x
	printf("\n=======>%%x format<=========\n");
	count = printf(" %x ", 0);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -10);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -200000);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -6000023);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 10);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 10000);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 100023);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 0xabcdef);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 0x7fedcba1);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", INT_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", UINT_MAX);
	printf("%d", count);
	printf("\n");
    count = printf(" %x ", 0);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -1);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 1);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 9);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 10);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 11);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 15);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 16);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 17);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 99);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 100);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 101);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -9);
	printf("%d", count);
	printf("\n");
    count = printf(" %x ", 42);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -42);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -10);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -11);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -14);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -15);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -16);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -99);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -100);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", -101);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", INT_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", LONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", LONG_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", UINT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", ULONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %x ", 9223372036854775807LL);
	printf("%d", count);
	printf("\n");
    count = printf("dgs%xxx", 10);
	printf("%d", count);
	printf("\n");
	count = printf("%x%xx%x", 1, 2, -3);
	printf("%d", count);
	printf("\n");
	count = printf("before %x after", 42);
	printf("%d", count);
	printf("\n");
	count = printf("%x%x%x%x%x", 1, 100, 999, 42, 999988888);
	printf("%d", count);
	printf("\n");
	count = printf("a%xb%xc%xd", 0, 55555, 100000);
	printf("%d", count);
	printf("\n");
	count = printf("%x, %x", 0, UINT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %x %x %x %x %x %x %x", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	printf("%d", count);
	printf("\n");


// address hexa high %X
	printf("\n=======>%%X format<=========\n");
	count = printf(" %X ", 0);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -10);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -200000);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -6000023);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 10);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 10000);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 100023);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 0xabcdef);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 0x7fedcba1);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", INT_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", UINT_MAX);
	printf("%d", count);
	printf("\n");
    count = printf(" %X ", 0);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -1);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 1);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 9);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 10);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 11);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 15);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 16);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 17);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 99);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 100);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 101);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -9);
	printf("%d", count);
	printf("\n");
    count = printf(" %X ", 42);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -42);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -10);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -11);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -14);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -15);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -16);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -99);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -100);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", -101);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", INT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", INT_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", LONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", LONG_MIN);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", UINT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", ULONG_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %X ", 9223372036854775807LL);
	printf("%d", count);
	printf("\n");
    count = printf("dgs%Xxx", 10);
	printf("%d", count);
	printf("\n");
	count = printf("%X%Xx%X", 1, 2, -3);
	printf("%d", count);
	printf("\n");
	count = printf("before %X after", 42);
	printf("%d", count);
	printf("\n");
	count = printf("%X%X%X%X%X", 1, 100, 999, 42, 999988888);
	printf("%d", count);
	printf("\n");
	count = printf("a%Xb%Xc%Xd", 0, 55555, 100000);
	printf("%d", count);
	printf("\n");
	count = printf("%X, %X", 0, UINT_MAX);
	printf("%d", count);
	printf("\n");
	count = printf(" %X %X %X %X %X %X %X", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	printf("%d", count);
	printf("\n");
	count = printf("%%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%%%%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %c%%", 'A', "42", 42, 42 ,42 , 42, 42, 'B', "-42", -42, -42
,-42 ,-42, 42, 'C', "0", 0, 0 ,0 ,0, 42, 0);
	printf("%d", count);
	printf("\n");
	count = printf(" %c %c %c ", '0', 0, '1');
	printf("%d", count);
	printf("\n");
	count = printf(" %c %c %c ", '2', '1', 0);
	printf("%d", count);
	printf("\n");
	count = printf(" %c %c %c ", 0, '1', '2');
	printf("%d", count);
	printf("\n");
	return (0);
}


