#include "ft_printf.h"
#include <limits.h>

int	main(void)
{
	int	count;
	char	*temp;

	// no format
	ft_printf("\n=======>No format<=========\n");
	count = ft_printf("");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("\x01\x02\a\v\b\f\r\n");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("coucou");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("#nyancat inside");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("\x7f");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("The Game.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("I know what you are doing.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("You should better not go to sleep.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Drop the keyboard and RUN!");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Any invalid command will remove a random file from your home.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("You will die before this tests ends.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("I love the smell of bugs in the morning.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("What do you want to debug today?");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("rm: /: Permission denied.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Already up-to-date.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(":(){ :|:& };:");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Do you want to print 333.5K chars? (y/N)");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Try with ASAN, and be amazed");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Remember that word: C H A I R");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Good morning, pal *<:-)");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("WASTED");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Too old to crash");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("don’t feed the bugs! (except delicious stacktraces)!");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Beer in mind.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("3nl4r9e y0\\/r pr1ntf");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("Don't do this.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("No fix, no sleep");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("/dev/brain: No such file or directory.");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("こんにちは、私はprintf単体テストです");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("いいえ");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("最終的なフラッシュ");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("(╯°□°)╯︵ ┻━┻ ");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("┬─┬﻿ ノ( ゜-゜ノ)");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("(╯°Д°）╯︵ /(.□ . \\)");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("(/ .□.)\\ ︵╰(゜Д゜)╯︵ /(.□. \\)");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("ʕノ•ᴥ•ʔノ ︵ ┻━┻");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);


	// char
		ft_printf("\n=======>CHAR format<=========\n");
	count = ft_printf("%c", '0');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c ", '0');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c", '0' - 256);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%c ", '0' + 256);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c %c %c ", '0', '2', '1');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c %c %c ", ' ', ' ', ' ');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c %c %c ", '1', '2', '3');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c %c %c ", '2', '1', '0');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c %c %c ", '0', '1', '2');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%c", 'x');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c", 'x');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%c ", 'x');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%c%c%c", 'a', '\t', 'b');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%cc%cc%c", 'a', '\t', 'b');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%cs%cs%c", 'c', 'b', 'a');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);

	// str
		ft_printf("\n=======>STR format<=========\n");
	char *s2 = "Mussum Ipsum, cacilds vidis litro abertis. Posuere libero varius. Nullam a nisl ut ante blandit hendrerit. Aenean sit amet nisi. Atirei o pau no gatis, per gatis num morreus.";
	count = ft_printf("%s", "");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %s", "");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%s ", "");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %s ", "");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %s ", "-");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %s %s ", "", "-");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %s %s ", " - ", "");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %s %s %s %s %s", " - ", "", "4", "", s2);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %s %s %s %s %s ", " - ", "", "4", "", "2 ");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" NULL %s NULL ", NULL);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%s", "");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%s", (char *)NULL);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%s", "some string with %s hehe");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %s", "can it handle \t and \n?");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%sx", "{} al$#@@@^&$$^#^@@^$*((&");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%s%s%s", "And ", "some", "joined");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%ss%ss%ss", "And ", "some other", "joined");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);


	// %%
	ft_printf("\n=======>%% format<=========\n");
	count = ft_printf("%%");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %%");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%%c");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%%%%%%");
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%%%c", 'x');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);


	// address pointers
		ft_printf("\n=======>POINTERS format<=========\n");
	
	count = ft_printf("%p",NULL);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",(void *)-14523);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",(void *)ULONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",(void *)LONG_MAX + 423856);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",(void *)0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",(void *)INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",-1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",2);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",3);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",4);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",5);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",6);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",7);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",8);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",12);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",13);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",14);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",17);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",LONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",LONG_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",ULONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",-ULONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%p",0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);


	// address decimal %d
	ft_printf("\n=======>%%d format<=========\n");
	count = ft_printf("%d", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d", -200000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d", -6000023);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d", 10000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d", 100023);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("dgs%dxx", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%d%dd%d", 1, 2, -3);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 17);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -14);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", -101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", LONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", LONG_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", ULONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d ", 9223372036854775807LL);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %d %d %d %d %d %d %d", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);



// address decimal %i
	ft_printf("\n=======>%%i format<=========\n");
	count = ft_printf("%i", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i", -200000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i", -6000023);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i", 10000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i", 100023);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("dgs%ixx", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%i%id%i", 1, 2, -3);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 17);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -14);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", -101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", LONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", LONG_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", ULONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i ", 9223372036854775807LL);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %i %i %i %i %i %i %i", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	
	
	// address unsigned int %u
	ft_printf("\n=======>%%u format<=========\n");
	count = ft_printf(" %u ", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 17);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -14);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", -101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", LONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", LONG_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", ULONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u ", 9223372036854775807LL);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %u %u %u %u %u %u %u", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	temp = ft_itoa(count);
	ft_printf(temp);
	free(temp);
	ft_printf("\n");
	count = ft_printf("%u", 42);
    temp = ft_itoa(count);
    ft_printf(temp);
    ft_printf("\n");
    free(temp);
	count = ft_printf("before %u after", 42);
    temp = ft_itoa(count);
    ft_printf(temp);
    ft_printf("\n");
    free(temp);
	count = ft_printf("%u%u%u%u%u", 1, 100, 999, 42, 999988888);
    temp = ft_itoa(count);
    ft_printf(temp);
    ft_printf("\n");
    free(temp);
	count = ft_printf("a%ub%uc%ud", 0, 55555, 100000);
    temp = ft_itoa(count);
    ft_printf(temp);
    ft_printf("\n");
    free(temp);
	count = ft_printf("%u", UINT_MAX);
    temp = ft_itoa(count);
    ft_printf(temp);
    ft_printf("\n");
    free(temp);



	// address hexa low %x
	ft_printf("\n=======>%%x format<=========\n");
	count = ft_printf(" %x ", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -200000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -6000023);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 10000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 100023);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 0xabcdef);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 0x7fedcba1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
    free(temp);
	count = ft_printf(" %x ", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 17);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
    free(temp);
	count = ft_printf(" %x ", 42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -14);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", -101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", LONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", LONG_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", ULONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x ", 9223372036854775807LL);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
    free(temp);
	count = ft_printf("dgs%xxx", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%x%xx%x", 1, 2, -3);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("before %x after", 42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%x%x%x%x%x", 1, 100, 999, 42, 999988888);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("a%xb%xc%xd", 0, 55555, 100000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%x, %x", 0, UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %x %x %x %x %x %x %x", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);



	// address hexa high %X
	ft_printf("\n=======>%%X format<=========\n");
	count = ft_printf(" %X ", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -200000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -6000023);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 10000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 100023);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 0xabcdef);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 0x7fedcba1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
    free(temp);
	count = ft_printf(" %X ", 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 1);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 17);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -9);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
    free(temp);
	count = ft_printf(" %X ", 42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -11);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -14);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -15);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -16);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -99);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -100);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", -101);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", INT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", INT_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", LONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", LONG_MIN);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", ULONG_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X ", 9223372036854775807LL);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
    free(temp);
	count = ft_printf("dgs%Xxx", 10);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%X%Xx%X", 1, 2, -3);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("before %X after", 42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%X%X%X%X%X", 1, 100, 999, 42, 999988888);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("a%Xb%Xc%Xd", 0, 55555, 100000);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%X, %X", 0, UINT_MAX);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %X %X %X %X %X %X %X", INT_MAX, INT_MIN, LONG_MAX, LONG_MIN, ULONG_MAX, 0, -42);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf("%%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%%%%%c%%%s%%%d%%%i%%%u%%%x%%%X%%%% %c%%", 'A', "42", 42, 42 ,42 , 42, 42, 'B', "-42", -42, -42
,-42 ,-42, 42, 'C', "0", 0, 0 ,0 ,0, 42, 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c %c %c ", '0', 0, '1');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c %c %c ", '2', '1', 0);
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	count = ft_printf(" %c %c %c ", 0, '1', '2');
	temp = ft_itoa(count);
	ft_printf(temp);
	ft_printf("\n");
	free(temp);
	return (0);
}

